-- Migration: Dual AI Orchestration - chat_sessions and chat_messages tables
-- Requirements: 9.1, 9.4
-- Description: Stores chat sessions and messages for Claude Socratic tutoring

-- Chat Sessions Table
CREATE TABLE IF NOT EXISTS chat_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  parsed_content_id UUID REFERENCES parsed_content(id) ON DELETE SET NULL,
  synced_assignment_id UUID REFERENCES synced_assignments(id) ON DELETE SET NULL,
  session_title TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  -- Claude API metrics
  input_tokens INTEGER,
  output_tokens INTEGER,
  cache_creation_tokens INTEGER,
  cache_read_tokens INTEGER,
  -- Metadata
  model_version TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT valid_role CHECK (role IN ('user', 'assistant'))
);

-- Indexes for performance
CREATE INDEX idx_chat_sessions_student ON chat_sessions(student_id);
CREATE INDEX idx_chat_messages_session ON chat_messages(session_id);
CREATE INDEX idx_chat_messages_created ON chat_messages(created_at);

-- Row Level Security (RLS)
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Students can view their own chat sessions
CREATE POLICY "Students can view their own chat sessions"
  ON chat_sessions FOR SELECT
  USING (student_id = auth.uid());

-- Students can create their own chat sessions
CREATE POLICY "Students can create their own chat sessions"
  ON chat_sessions FOR INSERT
  WITH CHECK (student_id = auth.uid());

-- Students can view messages in their sessions
CREATE POLICY "Students can view messages in their sessions"
  ON chat_messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM chat_sessions
      WHERE chat_sessions.id = chat_messages.session_id
      AND chat_sessions.student_id = auth.uid()
    )
  );

-- Service role can manage all chat messages
CREATE POLICY "Service role can manage chat messages"
  ON chat_messages FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

-- Comments for documentation
COMMENT ON TABLE chat_sessions IS 'Stores chat sessions between students and the Claude Socratic tutor';
COMMENT ON TABLE chat_messages IS 'Stores individual messages within chat sessions with token usage metrics';
COMMENT ON COLUMN chat_messages.role IS 'Message sender: user (student) or assistant (Claude)';
COMMENT ON COLUMN chat_messages.input_tokens IS 'Number of input tokens sent to Claude API';
COMMENT ON COLUMN chat_messages.output_tokens IS 'Number of output tokens generated by Claude';
COMMENT ON COLUMN chat_messages.cache_creation_tokens IS 'Tokens used to create prompt cache (first time)';
COMMENT ON COLUMN chat_messages.cache_read_tokens IS 'Tokens read from prompt cache (90% discount)';
COMMENT ON COLUMN chat_messages.model_version IS 'Claude model version used (e.g., claude-3-5-sonnet-20241022)';
