-- Migration: Dual AI Orchestration - ai_metrics table
-- Requirements: 10.1, 10.2, 10.3
-- Description: Tracks AI API usage, token counts, costs, and performance metrics

CREATE TABLE IF NOT EXISTS ai_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE SET NULL,
  service_type TEXT NOT NULL,
  operation_type TEXT NOT NULL,
  model_version TEXT NOT NULL,
  -- Token usage
  input_tokens INTEGER,
  output_tokens INTEGER,
  cache_creation_tokens INTEGER,
  cache_read_tokens INTEGER,
  -- Performance
  latency_ms INTEGER,
  -- Cost tracking (in USD)
  estimated_cost_usd DECIMAL(10, 6),
  -- Status
  success BOOLEAN NOT NULL,
  error_message TEXT,
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT valid_service CHECK (
    service_type IN ('gemini_vision', 'claude_chat')
  ),
  CONSTRAINT valid_tokens CHECK (
    input_tokens >= 0 AND
    output_tokens >= 0 AND
    (cache_creation_tokens IS NULL OR cache_creation_tokens >= 0) AND
    (cache_read_tokens IS NULL OR cache_read_tokens >= 0)
  )
);

-- Indexes for performance and analytics
CREATE INDEX idx_ai_metrics_service ON ai_metrics(service_type);
CREATE INDEX idx_ai_metrics_created ON ai_metrics(created_at);
CREATE INDEX idx_ai_metrics_student ON ai_metrics(student_id);
CREATE INDEX idx_ai_metrics_success ON ai_metrics(success);

-- Row Level Security (RLS)
ALTER TABLE ai_metrics ENABLE ROW LEVEL SECURITY;

-- Only service role can write metrics
CREATE POLICY "Service role can manage metrics"
  ON ai_metrics FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

-- Comments for documentation
COMMENT ON TABLE ai_metrics IS 'Tracks AI API usage, costs, and performance for monitoring and optimization';
COMMENT ON COLUMN ai_metrics.service_type IS 'AI service used: gemini_vision or claude_chat';
COMMENT ON COLUMN ai_metrics.operation_type IS 'Type of operation: image_processing or chat_response';
COMMENT ON COLUMN ai_metrics.model_version IS 'Specific model version used (e.g., gemini-1.5-pro-vision, claude-3-5-sonnet-20241022)';
COMMENT ON COLUMN ai_metrics.input_tokens IS 'Number of input tokens sent to the API';
COMMENT ON COLUMN ai_metrics.output_tokens IS 'Number of output tokens generated by the API';
COMMENT ON COLUMN ai_metrics.cache_creation_tokens IS 'Tokens used to create prompt cache (Anthropic only)';
COMMENT ON COLUMN ai_metrics.cache_read_tokens IS 'Tokens read from prompt cache with 90% discount (Anthropic only)';
COMMENT ON COLUMN ai_metrics.latency_ms IS 'API response time in milliseconds';
COMMENT ON COLUMN ai_metrics.estimated_cost_usd IS 'Estimated cost in USD based on token usage and pricing';
COMMENT ON COLUMN ai_metrics.success IS 'Whether the API call succeeded';
COMMENT ON COLUMN ai_metrics.error_message IS 'Error message if the API call failed';
