'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { FileText, Layers, Map, Sparkles, PenLine, Atom } from 'lucide-react'
import { useActiveProfile } from '@/contexts/ActiveProfileContext'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useActiveProfileSummary } from '@/hooks/useActiveProfileSummary'
import type { StudyTopic } from '@/lib/types'
import ReactMarkdown from 'react-markdown'

export default function HighDashboardPage() {
  const { activeProfileId } = useActiveProfile()
  const { summary: activeProfile } = useActiveProfileSummary()
  const [topics, setTopics] = useState<StudyTopic[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [newTitle, setNewTitle] = useState('')
  const [isCreating, setIsCreating] = useState(false)
  const [isGuideOpen, setIsGuideOpen] = useState(false)
  const [guideMarkdown, setGuideMarkdown] = useState<string | null>(null)
  const [guideTitle, setGuideTitle] = useState<string | null>(null)
  const [generatingTopicId, setGeneratingTopicId] = useState<string | null>(null)
  const [isDownloadingPdf, setIsDownloadingPdf] = useState(false)
  const guideContentRef = useRef<HTMLDivElement | null>(null)

  const canUseTopics = useMemo(() => {
    if (!activeProfile) return false
    return activeProfile.gradeBand === 'high'
  }, [activeProfile])

  useEffect(() => {
    if (!activeProfile?.id || !canUseTopics) {
      setTopics([])
      return
    }
    let isMounted = true
    const load = async () => {
      setIsLoading(true)
      setError(null)
      try {
        const response = await fetch(`/api/study-topics?profileId=${activeProfile.id}`, {
          credentials: 'include',
        })
        const payload = await response.json()
        if (!response.ok) {
          throw new Error(payload?.error || 'Failed to load study topics')
        }
        if (isMounted) {
          setTopics(payload.topics || [])
        }
      } catch (err: any) {
        if (isMounted) {
          setError(err?.message || 'Failed to load study topics')
        }
      } finally {
        if (isMounted) {
          setIsLoading(false)
        }
      }
    }
    load()
    return () => {
      isMounted = false
    }
  }, [activeProfile?.id, canUseTopics])

  const handleCreateTopic = async () => {
    if (!activeProfile?.id || !newTitle.trim()) return
    setIsCreating(true)
    setError(null)
    try {
      const response = await fetch('/api/study-topics', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ profileId: activeProfile.id, title: newTitle.trim() }),
      })
      const payload = await response.json()
      if (!response.ok) {
        throw new Error(payload?.error || 'Failed to create topic')
      }
      setTopics((prev) => [payload.topic, ...prev])
      setNewTitle('')
    } catch (err: any) {
      setError(err?.message || 'Failed to create topic')
    } finally {
      setIsCreating(false)
    }
  }

  const handleGenerateGuide = async (topic: StudyTopic) => {
    setGeneratingTopicId(topic.id)
    setError(null)
    try {
      const response = await fetch(`/api/study-topics/${topic.id}/generate`, {
        method: 'POST',
        credentials: 'include',
      })
      const payload = await response.json()
      if (!response.ok) {
        throw new Error(payload?.error || 'Failed to generate study guide')
      }
      setGuideMarkdown(payload?.guide?.markdown || '')
      setGuideTitle(payload?.guide?.title || topic.title)
      setIsGuideOpen(true)
    } catch (err: any) {
      setError(err?.message || 'Failed to generate study guide')
    } finally {
      setGeneratingTopicId(null)
    }
  }

  const handlePrintGuide = (mode: 'print' | 'pdf') => {
    if (!guideContentRef.current) return
    const html = guideContentRef.current.innerHTML
    const title = guideTitle || 'Study Guide'
    const newWindow = window.open('', '_blank', 'width=900,height=700')
    if (!newWindow) return
    newWindow.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: "Inter", Arial, sans-serif; color: #0f172a; margin: 32px; }
            h1, h2, h3 { color: #0f172a; margin-top: 20px; }
            p { line-height: 1.6; }
            ul { padding-left: 20px; }
            li { margin-bottom: 6px; }
            .guide-header { margin-bottom: 24px; }
            .guide-header p { color: #475569; margin: 6px 0 0; }
            .tip { margin-top: 12px; font-size: 12px; color: #475569; }
          </style>
        </head>
        <body>
          <div class="guide-header">
            <h1>${title}</h1>
            <p>Study guide generated by ForgeStudy.</p>
            ${mode === 'pdf' ? '<div class="tip">Tip: In the print dialog, choose “Save as PDF”.</div>' : ''}
          </div>
          <div>${html}</div>
        </body>
      </html>
    `)
    newWindow.document.close()
    newWindow.focus()
    newWindow.print()
  }

  const handleDownloadPdf = async () => {
    if (!guideContentRef.current) return
    setIsDownloadingPdf(true)
    const content = guideContentRef.current
    const title = guideTitle || 'Study Guide'

    const temp = document.createElement('div')
    temp.style.width = '816px'
    temp.style.padding = '32px'
    temp.style.background = '#ffffff'
    temp.style.color = '#0f172a'
    temp.style.position = 'fixed'
    temp.style.left = '-9999px'
    temp.style.top = '0'

    const heading = document.createElement('div')
    heading.innerHTML = `<h1 style="font-size: 24px; margin: 0 0 4px;">${title}</h1>
      <p style="margin: 0 0 16px; color: #475569; font-size: 12px;">
        Study guide generated by ForgeStudy.
      </p>`

    const clone = content.cloneNode(true) as HTMLElement
    temp.appendChild(heading)
    temp.appendChild(clone)
    document.body.appendChild(temp)

    try {
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ])

      const canvas = await html2canvas(temp, {
        backgroundColor: '#ffffff',
        scale: 2,
        windowWidth: temp.scrollWidth,
      })
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'p', unit: 'pt', format: 'letter' })
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const imgWidth = pageWidth
      const imgHeight = (canvas.height * imgWidth) / canvas.width

      let heightLeft = imgHeight
      let position = 0

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight

      while (heightLeft > 0) {
        position = heightLeft - imgHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
        heightLeft -= pageHeight
      }

      const safeTitle = (title || 'study-guide')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)+/g, '')
      pdf.save(`${safeTitle || 'study-guide'}.pdf`)
    } finally {
      document.body.removeChild(temp)
      setIsDownloadingPdf(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-emerald-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div className="flex flex-col gap-10">
          <section className="rounded-3xl border border-slate-200/70 bg-white/90 shadow-xl shadow-slate-200/40 p-8 sm:p-10">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
              <div>
                <div className="inline-flex items-center gap-2 rounded-full bg-emerald-100/80 text-emerald-700 text-xs font-semibold px-3 py-1 mb-4">
                  ForgeHigh • Grades 9–12
                </div>
                <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-3">
                  Study hub for grades 9–12
                </h1>
                <p className="text-slate-600 text-base sm:text-lg max-w-2xl">
                  Keep every class moving with topics, maps, practice, and exam sheets.
                </p>
              </div>
              <div className="flex flex-col gap-3">
                <div className="rounded-2xl border border-emerald-100 bg-emerald-50/70 px-5 py-4">
                  <p className="text-xs font-semibold text-emerald-800 uppercase tracking-wide mb-2">Start here</p>
                  <Link
                    href="#study-topics"
                    className="inline-flex items-center justify-center w-full px-6 py-3 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-semibold shadow-lg hover:from-emerald-700 hover:to-teal-700 transition-all"
                  >
                    Open study topics
                  </Link>
                </div>
                <Link
                  href="/sources"
                  className="inline-flex items-center justify-center px-6 py-3 rounded-xl border-2 border-slate-200 text-slate-700 font-semibold hover:bg-slate-50 transition-colors"
                >
                  Upload course materials
                </Link>
              </div>
            </div>
            {!activeProfileId && (
              <div className="mt-6 rounded-2xl border border-amber-200/70 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                Choose a student profile to tailor pacing and assignments.
              </div>
            )}
          </section>

          <section className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {[
              {
                icon: Layers,
                title: 'Build a study topic',
                description: 'Group maps, practice, and notes in one place.',
                href: '#study-topics',
                action: 'Open topics',
              },
              {
                icon: Map,
                title: 'Study map',
                description: 'Turn a class unit into a step-by-step plan.',
                href: '/tutor?tool=study-map',
                action: 'Build a map',
              },
              {
                icon: Sparkles,
                title: 'Practice mode',
                description: 'Mix easy and challenge questions to prep fast.',
                href: '/tutor?tool=practice',
                action: 'Start practice',
              },
              {
                icon: FileText,
                title: 'Exam sheets',
                description: 'Create a one-page review you can print.',
                href: '/tutor?tool=exam',
                action: 'Create a sheet',
              },
              {
                icon: PenLine,
                title: 'Essay architect',
                description: 'Thesis, outline, evidence, and revision support.',
                href: '/tutor?tool=writing',
                action: 'Start writing',
              },
              {
                icon: Atom,
                title: 'STEM coach',
                description: 'Advanced math + physics, step-by-step reasoning.',
                href: '/tutor?tool=practice',
                action: 'Work a problem',
              },
            ].map((item) => (
              <div
                key={item.title}
                className="rounded-2xl border border-emerald-100 bg-white/90 p-6 shadow-md shadow-slate-200/40"
              >
                <div className="w-12 h-12 rounded-2xl bg-emerald-100 text-emerald-700 flex items-center justify-center mb-4">
                  <item.icon className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">{item.title}</h3>
                <p className="text-sm text-slate-600 mb-4">{item.description}</p>
                <Link
                  href={item.href}
                  className="inline-flex items-center justify-center rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 transition-colors"
                >
                  {item.action}
                </Link>
              </div>
            ))}
          </section>

          <section id="study-topics" className="rounded-3xl border border-slate-200/70 bg-white/95 p-8 sm:p-10 shadow-lg shadow-slate-200/40">
            <div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between mb-6">
              <div>
                <h2 className="text-2xl font-semibold text-slate-900">Study topics</h2>
                <p className="text-slate-600 mt-2">
                  Save tutor outputs, maps, and practice items into focused topics.
                </p>
              </div>
              <div className="flex flex-col gap-2 w-full sm:w-auto">
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="New topic title"
                  className="w-full sm:w-64 rounded-xl border border-slate-200 px-4 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
                <Button onClick={handleCreateTopic} disabled={isCreating || !newTitle.trim()}>
                  {isCreating ? 'Creating...' : 'Create topic'}
                </Button>
              </div>
            </div>

            {!activeProfileId && (
              <div className="mb-6 rounded-2xl border border-amber-200/70 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                Choose a student profile to tailor pacing and assignments.
              </div>
            )}

            {error && (
              <div className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                {error}
              </div>
            )}

            {isLoading ? (
              <p className="text-slate-600">Loading topics...</p>
            ) : topics.length === 0 ? (
              <div className="rounded-2xl border border-slate-200 bg-white/80 p-8 text-center">
                <p className="text-slate-600">No study topics yet. Create your first topic to start collecting items.</p>
              </div>
            ) : (
              <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                {topics.map((topic) => (
                  <div key={topic.id} className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-md">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <h3 className="text-lg font-semibold text-slate-900">{topic.title}</h3>
                        <p className="text-xs text-slate-500 mt-1">
                          {topic.itemsCount ?? 0} saved items
                        </p>
                      </div>
                    </div>
                    <Button
                      className="mt-4 w-full"
                      onClick={() => handleGenerateGuide(topic)}
                      disabled={generatingTopicId === topic.id}
                    >
                      {generatingTopicId === topic.id ? 'Generating...' : 'Generate study guide'}
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </section>
        </div>
      </div>

      <Dialog open={isGuideOpen} onOpenChange={(open) => !open && setIsGuideOpen(false)}>
        <DialogContent className="max-w-4xl w-[95vw] max-h-[90vh] overflow-hidden p-0 bg-slate-50">
          <DialogHeader className="border-b border-slate-200 bg-white px-6 py-4">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-emerald-600">Study guide</p>
                <DialogTitle className="text-xl sm:text-2xl text-slate-900 mt-1">
                  {guideTitle || 'Study Guide'}
                </DialogTitle>
                <p className="text-sm text-slate-600">
                  Review the sections, then quiz yourself with the prompts at the bottom.
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" onClick={() => handlePrintGuide('print')}>
                  Print
                </Button>
                <Button onClick={handleDownloadPdf} disabled={isDownloadingPdf}>
                  {isDownloadingPdf ? 'Preparing PDF...' : 'Download PDF'}
                </Button>
              </div>
            </div>
          </DialogHeader>
          <div className="px-6 py-5 max-h-[72vh] overflow-y-auto">
            {guideMarkdown ? (
              <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm">
                <div
                  ref={guideContentRef}
                  className="prose prose-slate max-w-none text-sm sm:text-base leading-relaxed text-slate-700 prose-headings:mt-5 prose-headings:mb-2 prose-headings:text-slate-900 prose-strong:text-slate-900 prose-li:marker:text-emerald-500 prose-hr:border-slate-200"
                >
                  <ReactMarkdown>{guideMarkdown}</ReactMarkdown>
                </div>
              </div>
            ) : (
              <p className="text-sm text-slate-600">No guide available yet.</p>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
